language: generic
sudo: required
services:
  - docker # automatically install the Docker

before_install:
  - docker build -t tylerauer/docker-react -f Dockerfile.dev .

# Commands needed to run test suite
# Travis watches and if it gets an exit code other than 0, it knows a test failed
# Expects tests to run and then exit, but npm run test doesn't automatically exit
# adding -- --coverage to npm run test makes sure npm run test exits
script:
  - docker run -e CI=true tylerauer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-403525920890"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
